#!/bin/sh
DIR=$( cd "$(dirname "$0")" ; pwd -P )
. $DIR/env.sh
LIST=`mktemp`
LIST2=`mktemp`
TOR2WEB_JSON=`mktemp`
http_proxy="" https_proxy="" wget --no-check-certificate -O $TOR2WEB_JSON https://eqt5g4fuenphqinx.tor2web.org/antanistaticmap/stats/yesterday
$SCRIPTDIR/import_tor2web.py $TOR2WEB_JSON > $LIST
rm $TOR2WEB_JSON

$SCRIPTDIR/extract_from_url.sh 'https://danwin1210.me/onions.php?format=text' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'http://www.thehackerstore.net/2015/07/huge-list-of-darknet-deep-web-hidden.html' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://thehiddenwiki.org/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://torhiddenwiki.com/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://darknetmarkets.org/markets/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.reddit.com/r/onions/comments/73jpvo/loads_of_good_onion_links_part_two/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'http://deepweblinks.org/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.quora.com/What-are-some-cool-dark-web-websites?share=1' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.reddit.com/r/onions/comments/56sz15/suggestions_links_post_it_here/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'http://www.linuxx.eu/p/deep-web-link-list-onion.html' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://pastebin.com/7K4mTtL3' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://pastebin.com/wCum39W6' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://pastebin.com/TKvzf5Dz' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://pastebin.com/sQ0rw54u' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'http://seriezfree.blogspot.com/p/blog-page.html' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/tor-emails-chat-rooms-links/' >> $LIST # ****
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-forums-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-drugs-sites-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-hitman-escrow-rent-hacker-documents-deep-web-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-bitcoin-counterfeit-credit-cards-paypal-accounts-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-torrent-movie-games-sites-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-weapons-software-hacking-virus-cracking-sites-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/page/13/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/gadgets-deep-web-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/page/15/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/red-room-deep-web-social-media-extra-deep-web-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-screenshot/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/tor-search-engine-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-books-sites-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-hosting-file-hosting-image-hosting-service-links/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://www.deepwebsiteslinks.com/deep-web-markets-links/' >> $LIST # ****
$SCRIPTDIR/extract_from_url.sh 'https://www.reddit.com/r/onions/search\?q\=url:.onion\&sort\=new\&restrict_sr\=on' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://ahmia.fi/address/' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://raw.githubusercontent.com/alecmuffett/onion-sites-that-dont-suck/master/README.md' >> $LIST
$SCRIPTDIR/extract_from_url.sh 'https://en.wikipedia.org/wiki/List_of_Tor_hidden_services' >> $LIST

$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/2/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/3/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/4/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/5/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/6/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/7/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/8/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'matrixdirectory.torpress2sarn7xw.onion/page/9/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'http://donionsixbjtiohce24abfgsffo2l4tk26qx464zylumgejukfq2vead.onion/onions.php' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'http://visitorfi5kl7q7i.onion/onions/' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'http://underdj5ziov3ic7.onion/crawler/index.php?online=1' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'http://torlinkbgs6aabns.onion/#financial' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'protonirockerxow.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zrwxcayqc4jgggnm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vola7ileiax4ueow.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mswmailgcjbye4sc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ozon3kdtlr6gtzjn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '344c6kbnjnljjzlz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ncikv3i4qfzwy2qy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iwab42vsaivtzkf5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cwu7eglxcabwttzf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ctemplar42u6fulx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lu4qfnnkbnduxurt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'grrmailb3fxpjbwm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eozm6j6i4mmme2p5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'scryptmaildniwm6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cadamailgxsy6ykq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sinbox4irsyaauzo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cockmailwwfvrtqj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitmailendavkbec.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torbox3uiot6wchz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'clgs64523yi2bkhz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pmasonkivrbmjlkv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'csclonezdiriab5k.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tetatl6umgbmtv27.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oxicsiwet42jw4h4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lelantoss7bcnwbv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fuacantanj2vhfpw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nzh3fv6jc6jskki3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'doggyfipznipbaia.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'campfireagz2uf22.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jitjatxmemcaaadp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qj3m7wxqk4pfqwob.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cqhxumz3t2apowat.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tepccm7ilswvi3td.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'youngcam7ayhwpol.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'infantilefb6ovh4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'r2j4xiyckibnyd45.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ogn5vbujhrvbihko.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'boytorqln5fxsokd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'onionirczesfffux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'piibzhewajawxte3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'v6tlwjbbtdqs7wsq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'danschatjr7qbwip.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deu35fwnhn4ormal.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'boytorchxf4zs4mz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sigaintevyh2rzvw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ypbnurlwfis7xsei.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bestchatzinhe3vc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mail2get4idcbfwe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dhbzkbw3ngxxt56q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mdj7ldtgoq22m3hi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'theboxmmvl6zg3wi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nbhcaocqy3o6hanixbw3hntumbs4rliggenai6cncd5duwxki3xcaryd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7bdohutqh2gfcv4s6qibej47jtrtosk27zq6eovq2tzf6euzawqixbid.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hchanu2or24rjm4dirxfo7uzbvd444uvg3uwdttdv4ikbabms6ddavyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kglddfz2wnvt7wiohbm6g6m5x5flufghnc4zxqdn76svdd3mtjr672id.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bba3dvekkuetaax2swnrlxq7ym6brbrmjf25de3tpwvobzap4rcsaeqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fqdxyhefyfy5nq3bi75edyhmbmutnbpxbvkrpsb2veelic5gn332gmad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gn2suqz5aewafkejelorsa7nhwk3o4kjrjc3wz5cs373dbqfodnihjad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rrcc5uuudhh4oz3c.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rhe4faeuhjs4ldc5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'anonymzn3twqpxq5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'z2hjm7uhwisw5jm5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'support26v5pvkg6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'suprbayoubiexnmp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'legionhiden4dqh4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tumbachegvyaadyq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gf2juatsqdph6x2h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qd73mvvc7v7zewwl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'thundersplv36ecb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'turkiyex6fkt46ra.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jungswtfwgjwile2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pncldyerk4gqofhp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'n7uub757gowpvoa2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rzb5nlpvy5oqnket.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iaypjcyn2twign5q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fbcy5ylyoeqzqzcr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zyuzqglpmne5pkoi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rzilaygoiqfvmmcl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5vvb4hixkejp5p47.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'norabizt5qqxefxy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3f66az7af6ckuhbr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'arhivachovtj2jrp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dchanqquavltpzco.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dkzerogt6z6ybhcj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'x7giprgefwfvkeep.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ukmafiao6elqbltk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cnwv3ycmy4uc7vou.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'realpissxny3hgyl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rutorzzmfflzllk5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bm26rwk32m7u7rec.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vrimutd6so6a565x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'answerstedhctbek.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dnmavengeradt4vo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'i2vzg7f44bj4l3r7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bfvfq7hjcdoinzo4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rfwtogljhrrzxyrl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wayawaytcl3k66fl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'joincgmc55oplang.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wpzvprpnhhcypnn4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rsclubzznck53v35.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'giw2dn4hkyajnuvw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'b7beezxbwccrwye2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'onionlandbakyt3j.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'thehub7xbw4dc5r2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'avengersdutyk3xf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vwlkx7ovcnvagl6q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'answereratuhgmph.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pmwdzvbyvnmwobk5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ocu3errhpxppmwpr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'exe2gut5zya5cfqh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'brchanansdnhvvnm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bodytomind5hql5r.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugbbadtrrr5v5b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hellamz4kpl26ltr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kbyz2vu3fnv2di7l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fdwmarkvokb5i7wh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yulxt5toyxavkb7r.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6piogx66d26o7hyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'highkorea5ou4wcy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cebollaw3p37wrsq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zx7ec2etdihlbfr4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zzq7gplcs5avm6tz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bm6hsivrmdnxmw2f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tq2ghppfea4hz7nn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'leb3rkvqzw2qd4dg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zzq7gpluliw6iq7l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lk77akehj7cjj2qp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mllpfi3dsfp7wjms.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'babyixntjlabwkpi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bchz4vggexx63qvy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'csrinru3c2ownkep.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dnfcht2zyeejnzz5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'germanyruvvy2tcw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vvvvvvvv766nz273.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hty3epcxja62jlxm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nanochanxv2lxnqi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'suicidio5364lj2l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'b72yp5z6cnufoowa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ou3ef7wgvt3gqmpc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'psb4ukrhoqqcdubr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'e4unrusy7se5evw5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'intelex7ny6coqno.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darksellerocxsuv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'piratanibanankoc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 's7ozxgjjhti43czg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kpdqsslspgfwfjpw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'anonywebix6vi6gz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'arcadian4nxs3pjr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5dhf54nxiuuv6jvs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'npdaaf3s3f2xrmlo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'saefjmgij57x5gky.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'krainkasnuawwxmu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ji7nj2et2kyrxpsh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zvz4ruc5b5q5yqzs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nightmareocykhgs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tbkukxw3vpnrhbvn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mlj4iyalawb2ve2u.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dopefruqgev5v4ul.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jackykb5wa6ujhfn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'playboyb2af45y45.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pharma5jbbmwjoo3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'viceversz7572gbw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'newshit5g5lc5coc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'do7dt6vuskgrz3sa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blackmartqjhpnzh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugszun7tvsgsaa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'limac6qxk43s3usf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eosdawn6knv2mno3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'auw6fzx756f6gqcd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dutchdr5gsol4dde.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'quality2ui4uooym.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pharmacpr5lpfin5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6yid7lwx2zemlel7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tdupp57f454vusnx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'chemradvzlfaqeqc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'china5n32dr6ycbq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xdsa5xcrrrxxxolc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'serpentfeli2knox.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ganjahfreaefo2d4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'haplab3nh5vvm5nt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pharmauoq6wnqp7q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitphar76n5t3qag.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eucannapggbtppdd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ma3lisqktqdlg3t6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7uvijlsswycvih2p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'abyssopyps3z4xof.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vikingpkipyehyyq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugss5mif4vrbws.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dedopedhvmcsxylb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'll6lardicrvrljvq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fzqnrlcvhkgbdwx5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'weedsragjdyuimdm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cocahze7fqy4qwwx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'smokerhv5hlklzh2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'weed46fkpfzc3lvi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'chemspain7iw2zby.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugs4youpsxzpp2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darkheroesq46awl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugsfl4lgmxfetn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugsqfazpkaitwq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cjakglmv3vidqwgt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pushingtabu7itqj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eeyovrly7charuku.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dxp2ajkn2dg52srz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tytbeta57rw2onit.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eupillu4np223oxe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mghreb4l5hdhiytu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'elherbotsiddarol.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yourdruhftworzg4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'artsmankindxgcv5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'x75csj7vzprjji5v.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'slkushhma4pmfirg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'stonedkj4x37iaov.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'newpdsuslmzqazvr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'o7d32orwrcj2lvf2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nfi3plp7famvohxm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'barbarianvainkcy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deepdrugjgxmchrr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugshowdhdy2n6c.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'smoker32pk4qt3mx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'viagr4rub7dne4xk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'o3shopvw3wpbvgfh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oma3fbej3tkzqtec.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deluxeq3evbxfnab.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cannazonceujdye3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'duxspajyacilqvbe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'calistrael6wmpab.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'icocainpsv5u5vat.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'treaty4rxst3zpvm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deepsea2ou77c6vw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'limaconzruthefg4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4bzdkt7vbxx3ivfj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'growers7nbzdvenz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wacky2yx73r2bjys.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tdupp6lmgnpex5ss.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dgreentdiwapb3zp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4yjes6zfucnh7vcj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'poisonj7bdow2nw7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pislandp2ridcklw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pmew6znterjncr3l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'partydoc7calqmjc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nlgrowc3xywaj2zn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'si4bm7a6rbxgpjzg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cocain2xkqiesuqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ye224web57i3gblr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'maghrebwzbkucctg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drugshowjdlvp3m2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'greenmwbv5u5t5th.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xpotbpgfnliidudm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'grimlockdlsgupyj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cq44ewxedjcuczty.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ygrqgcnoodnqdmlc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6nigkq2azpbeg2fa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darkmambawopntdk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yo4jmu6dsfaeekt3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'idomquol7lannf22.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zy3dkytcaubkq2y3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'assassinec3wumxw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'assassinuyy7h425.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2ogmrlfzdthnwkez.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rsprjqyxhf25l3qd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'prodarktzz3lnwrr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'digigangxiehugqk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'chbetteratd6wskq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hackerrljqhmq6jb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcasiah5fa5mhkp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'escrowq5tus5jpgw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'arcbatjfohvf2ahk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'escrow43eaperqie.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2hftxvyft7dl3fk2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hucoxxyf4y2nko6x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcasiauwqceleko.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ueujbytsstmxqon3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rocksolidyyacwsa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lockluk3ihwblma4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2mbag6csiomy2e7l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tm47kmrvlxuibig7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bestes77yawunk6p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'safebtck4qejiero.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'scant5xpeodjzgno.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'abbujjh5vqtq77wg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xfnwyig7olypdq5r.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'basetoolsnleabvh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iww2iqhwxmnbh4qs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'canary2fpcg4x2in.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fakeidskhfik46ux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'money2mxtcfcauot.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'teddanzignblrntr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mrreph6wof6xgt43.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cmarketsiuhtiix5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vfqnd6mieccqyiit.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fightckxiykml2xu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'en35tuzqmn4lofbk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2gxuigvhzdaaojky.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'scandgdpu7ab2gaa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gcardstguk366hru.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'edsec5zn26zqjwry.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'doxtorg7natnwyz5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fxwyfqrcj67nxal3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nojjxqzd6ofvkjss.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fizxwpbzkn5htzgm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vandyke4mvuffjkm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6wzv5ynuqqcfehag.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dugonj4mglbrusq6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'en35tfp3p3a4wqwb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6iv5kjou3ew4ne7s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'a4wzhhaukx4arl5i.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pirateceo5dz3q4b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6tfvy2hpwntnv5e6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cxiz4ysttf3jpnyc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'agenttoe2dlvxdei.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'escrow66ur35rllr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mcwayeswc2pqnxjf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eyziddrfxw4ggqyi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ngmqzzg6aesmflq5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bluemoon4vpzulpv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'd5c6kvvaxvjlkzkw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xcrowbits4efcnxk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mgg2c5dot5vqqgjq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6ebv6ztrjs6l43nz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fakepassbxbwcvtk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'locklukwr4v4w4qj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oiiuv2gwl2jhvg3j.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ultilgcikxzjug6j.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'huomyxhpzx6mw74e6jfxtj5kmxov6wdmc62ylk6oc7feht5gntuawaqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ytteyiazq2xyazjws45lxjpqie5krxdcoe4nr5vysldu54olnbtrg5qd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ra376h4adr4zpx66rly77taboanaqio63k63m23vhomv5i4hmyip2yad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dlegal66uj5u2dvcbrev7vv6fjtwnd4moqu7j6jnd42rmbypv3coigyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '64fgu54a3tlsgptx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deepmar57fbonfiw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sn2vwdleom47kzqp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'd5ubjv46kownm4jl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'p2dxfdbzpqosi3f5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'o3gaovlzc3d3x4oa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'df2as3ek5hwdsfjx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pm5xuy2gwmnc6f4f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bh3ly32l2b5gjqdc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vc3qj2iti5dkxryk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eqnbwy4b4k4lrlq5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'luxcard5dlmce47d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '65px7xq64qrib2fx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'omertavzkmsn6tp6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cashoutxdrebmlj2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yohoho7do5u6d35g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cvvmezl6gtffprgt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bucepafkui6lyblt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2nh7qkz5qlrp3a4g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fusioncjnm7ko7li.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cardshopffielsxi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xsqp76ka66qgue2s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'atmskima36v2nqdc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'r4u6jtmqzuedlgle.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'slwc4j5wkn3yyo5j.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xilliayhoiuv5qmk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'buyccoq36hlj6etg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccguruetr5jwye5g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'p2wasopjcodzszfm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vendorcugc6oppvb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'acteam2nmbucjnht.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dreamrvfuqrpzn4q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'prepaid3jdde64ro.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccxdnvotswsk2c3f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blackph5fuiz72bf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torcvvq44o7ofjuu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sexdq7iwyb4u7ah4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yaleshopznl7dyus.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bestshop3neaglxk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'giftcardmzsfdsxq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'easyvisa5i67p2hc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccqvltabnwq57ivi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cvendorj6vnr3thv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'creditlwkdnptwla.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xstftgk5c3hnf2s6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eda2jx74zvsjmd4h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cccenterjb27ubnm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'js4llg3xixasrcul.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'carddumpa36spoya.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ecmye7f3b7fywr3x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dumpscciolcwmacb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lq46uemafsc6il2g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'roscard5xxpj4g3g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'j5ehssrshpxpdkto.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zenithccalwhzy26.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mrisu6dzj2sy7uvl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bankors4d5cdq2tq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitcardsqucnyfv2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hcutffpecnc44vef.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccshophv5gxsge6o.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bingodon6ngajrqk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shop33x66asjehl4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccppshopsndysr45.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3s2v3uhkxr4pfoa3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yrz2nwkffev22vlo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shopcc55a5caqsr2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'chogfr6l5sktbfxo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rw67gudqwkpjnaqb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rt7afewsclpdgzxi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rtwtyinmq4wzzl6d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'amazongw6uqefsmo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ofqixpcxwjq5au7h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'moneyplheq37vfyk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'magic3h5qino7py2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5jd7g5y3o2wbzp5b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bjjkaebas6uywama.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'aaaajqiyzj34rhjm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitcohjnw63rvhyi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'unoppqar7cy3zvux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vendpmmhx5ylctjf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ghostbotc3iwjptr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'u2vyof5j4lwaluak.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'moneyl53xddioie6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'buyccvhbq25t5l3y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'z2sjyt2biv2uo44w.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bestdgp46k5ehen3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eacteamcesfsr3gt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'clonccb3b4hedaqu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yfdvbqa3vlzsvpmi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ykrryvbboc2vq64a.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vend2qz3bva3jhol.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'honeym4ms4nq7fdl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mecca2tlb6dac76g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dmania2naw2cprdm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sgangmyei7zrlinr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hn352uqgmmpxly2v.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'snovzruogrfrh252.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'uniccxide6hker6y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'procrdpkbbqtweda.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'offshore52uakque.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4oqzkjmb5fcy57w6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xqxf2ggcud2kntck.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fakebillkelmwaos.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'uzpsnetq2lpx6pv6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dollarsfn45wiq4f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'o6klk2vxlpunyqt6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qputrq3ejx42btla.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'countermltd42g4x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cfactoryxecooa6l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'counterfxhjvtrlw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cashoutr2inecwwy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'counter5y4he3hny.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'countfe766hqe4qd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qkj4drtgvpm7eecl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'stack4bw5slctbl6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sla2tcypjz774dno.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tj2djlce6qtevcai.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lordpay3t52brqwf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'usd4cx7otgnx6wtp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'money4uitwxrt2us.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xyaukzqqcdkop4ui.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xseiwyma2s3wdxmz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2jjx4rrqyc6ziaq5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cashflip6434deqb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cashgodr53umth4z.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'accountlwghunkeg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tye72sog65g5ehlp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'paypalacfi5pv4t2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kplatypxb2aecznv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tknijuhhdg4476vl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccghmfd2x74s7i22.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ozgyidpmrnvsyec5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vd6q2roxxjrly7nj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'u76xgym22s4adf55.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'platypusxchhwv6z.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ccpalym5nu3elh5y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ppextalynbst3xqm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hnxo2ddcvvswjnmf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'e7sin3urmxxcnu6a.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'netauth3qialu2ha.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3dbr5t4pygahedms.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'smartmixnjmuoixj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blenderiocpxfema.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcmxrcouqeacrid.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcmixhnpqlpfacx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tr5ods7ncr6eznny.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcwash7jmra3hgm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'paysiq46fc3ar6nd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'washdgxowwxxfcct.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcmxr76saccg5so.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitmixbizymuphkc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'atvx6hnosgyyafzx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dl65ns3e75qvj5rc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cryptomixns23scr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcmixxihego4qyg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'anonymizer5lg2fz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vp5rhkntohnccxea.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'usjudr3c6ez6tesi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'coinpigih6i444lm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcfebovmekmfqho.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xmrbepphykgq6yar.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sgkvfgvtxjzvbadm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bestmixer7o57mba.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'changeyusv3n5t73.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ltcpool5brio2gaj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zencashsmwdlr2sd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fwx2oxihh3yi5eyu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4r23alxe7mwyqa4s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '33oifeg53souby5f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3ow4o6l4c5hdiyad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qwmcl3jqq6bclzto.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'penguinsmbshtgmf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'i5a7pqwwbexdssrd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'financeqr7uutmcv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'stppd5as5x4hxs45.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wallet4wuka3dfrn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'anthill365g4egaa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'insideab4oluq25o.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gj344rvmagqfbgbx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btcase3buwolzhbq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'coinbinap7rxddp5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitcoin4wmsujlbb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'coinminj7oengi3s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitcloak43blmhmn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blockchainbdgpzk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'burgerfroz4jrjwt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3tnqzaoam4g3v5sj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5ifblitg2ywjjo2t.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'apple5e3lqymppzp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kaqkiyehzw23pnag.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yuvox5mt6nulou72.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'y3fpieiezy2sin4a.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ow24et3tetp6tvmk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oq3y6kvdjmhcavto.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'loundryslz2venqx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'foggeddriztrcar2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cleancoikmh6uamc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'coincloud25txgdf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitmixergv5vvbza.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sdd22dkdxdzpp3fg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'easycoinsayj7p5l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jzn5w5pac26sqef4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'buybtcstbl2d3igz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fbyr455vwvkpzp5k.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vaultu7dxw5bbg37.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cleancondgqja34b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitfinex4ietak3t.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blenderebuco2hfg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qi4j4x2xatt4r4zy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cashkxxqpzbgggg7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xrwveit2nw6etj4b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'f6n3slk5u2ncczzj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jsqvotsaf5yl7mwg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bostqmjfz64etvkf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tfxtsdtj72rznb7x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'a325elf2xw4jatgm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gc4youuhrzbp5rlm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5uhiksrbcojfgc5d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'agarpay2dblj7ev5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'i3magh4qtge2ejzc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'b5vep4c7ulp6snsv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'adrsucfhkj6lziax.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wwxoxavgqbhthyz7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'smmpxvzmhqrqmgu5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lm4rarblsx5yyimd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'saulcctopd6jwfrp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'debyrrafbkwqdg22.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hasx6qftht3mnzfz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '222rrzy7qx6qlrnb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mastjorwqdvvpmgo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'coincloo5wdlx2n7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tqi5om65lgzpej3y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'buddygyxom7som6u.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eurocfshftwvoqw2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ql5mduvendoreqxx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'scriptsa53voxpsk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'countfagevz3vjxe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'braveb6iyacflzc2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mvt22jcoapsaxbzb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gbpoundlnlrgewcc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darkcrej6njrcbgw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'milkroad6zwmtbu7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rothminr5wgew3f4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bfclsxyqtnwkrr2l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mirch2gqvs6fxmfg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'e5gawf3b4xnhdpsy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5zkhymnudrct55xr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'moneylxlh6i5dc5w.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2222scvlmdfyuxj2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'agcardsxujh3vu5u.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tqoep6u4atapq6w62zvkywr5oxcoruaqqjvunzpg4whmey73zmckp5id.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blionae6xzm7yfezz4kpyb3hz2he3pnhyltnnf5q6wecfhfgsiuwvxid.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blo7hh5upazzgyy5p2mb6dvckv5krkztd55u46wlmfivq7up2mdypdyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'uj3wazyk5u4hnvtk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'duskgytldkxiuqc6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rutorc6mqdinc4cz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gv6zipaqcoaau4qe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pirates2vk54clmu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bayfilesittwudwh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'galaxy2gchufcb3z.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sblib3fk2gryb46d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kpynyvym6xqi7wz2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wbyi72yt6gitdcqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'smk4dw5cbxd6lttl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wtwfzc6ty2s6x4po.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'r5n26fdanb4i522h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'btweb36l5cxqtcg4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ey4oty36pfgmec2c.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zmovietoropzaid3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'd5eyi24facorsljv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'solarmovie6rystf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hiotuxliwisbp6mi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dsenxis5txr4zbxe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zpe4auiu74xgr6dp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'snuffnu56nh7tpvi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rlujtxikez5kicwj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qhhunyjzmdyx4i4d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'suprbaycsyecyajt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oycijxgzuens2tsr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'archivecrfip2lpi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gamebombfak3pwnh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4sjd6hwtxbwtbpip.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'evilanonwadtz5xo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'giesn3ivtzp5z2us.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vwu7rdwyt2icpexq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6p4iv57uqi364ipj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ecs2psjyyqc4o32s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wbswrqr6hpt33xdi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'negimarxzov6ca4c.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rycxtlpyq7awtoea.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'empathyimadl2mp2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'radiocbsi2q27tob.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '663wbgqczxp445am.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'w5ifkainqlgtvg7a.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hlsf2cw74ydheg6f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iybwz5aq2yoig7q6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rtozvgednwoz3jub.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'imucastldveqqj6k.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kiy52zq46nqu426l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bettorzztykidrx2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'theches3nacocgsc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'by5oe7gmrt3pmn7p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'd7shwhjlrs45ooux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'flp6x6ammogdaxvl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fubmhhm7j6esuprg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6gua6qlq3scz7jam.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ypn4b7ye4xx2ier4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xmatchesfmhuzgfb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gxbsscozf5kex555.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'footballsge4ocq3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'betcoinahk4j27yb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5p6dpc344vsbigv7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rswwpapessp3xxpw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hg5km4y37lgir6r3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sntfgwfami5fdbn5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hideout6eiazeoyp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fixedlwgc3burzts.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wvxwdchqvprqfkl4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torbet777o4era3q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3r7ailix2glqhrwb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hb6y4jt4pnfb52v6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vbizukfplsqfdhbr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wmjtj2j57mcvs7ms.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vxes67oilqrbkwsb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hnsamralakjx4aj4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'irrgartenxhc4pur.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'abulafia7grubwhu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blueboxlxc4o7mvk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'demonhkzoijsvvui.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torrentbktntawbh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'c3jemx2ube5v5zpg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tmdwwwebwyuuqepd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'a4yedjgciupu7zzt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '76qugq4pb42lpgwx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6lw4pg2wsy475d7q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'grc43ygyy3iy5vxh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hzssn2ryi3hj7tah.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hsv47rw3y6r3h5ji.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ghostbookdoyyvrs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bet4winf2rjaitd4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'b4fxokjsy22ewpre.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lq54unz77o4x5k2n.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wc4kl7eq4gkaguhkck63x7jldzihpxluziutcazi3lfz4ylq4tn4dtid.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sy6xyv6auqbozoiaxdbvvhefe3g7et3ckbxkyv7aggpa7zx4jl5n2lad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7iedfch5ll6ktthvkfw2mfyl2bvqoloaa7sxe3cszson4sq3fr532kyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iid44nizvqih2dmkoqopi2xpnt35cm6pai7u37q7yzyshpddxsyawgqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xn6iqyc666d2ho4ztdsbilymoxmd3eftt2cmocmyycxofx427olwr6yd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'weapon5cd6o72mny.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blackmktxzue2hkz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'armoryohajjhou5m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gunsjmzh2btr7lpy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gunsdtk47tolcrre.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2kka4f23pcxgqkpv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gunsganjkiexjkew.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'luckp47s6xhz26rn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'drkseidwayn6uc5x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pistolcqex2ecr5r.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5xxqhn7qbtug7cag.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kwlxvnmxiu2vfvcy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'swegunsh343s3drf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ijr246luczc74cgm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tuu66yxvrnn3of7l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'armsmhmd4c3hb5xu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hhnovpxmqrw4xaqg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'exoduockgfq3ikf7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'stormgm7blbk7odd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darkdev5ibekblct.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sageranjccfovtn3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'swisslux25w4gwll.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'expressobutiolem.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rqef5a5mebgq46y5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iec56w4ibovnb4wc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wdpwzykrrqq4p7w7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shn3x3whdm5tuut4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tordeskw6z3bg3sb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rougmnvswfsmd4dq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3k5ucky4az46uu3m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'recovery6m3lvkxg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zsmjk76e7vldzli6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darknetncj7k6wzk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gvaslzwxr2ezognd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wpscanskzvjc4s2s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bptfp7py2wclht26.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'steamsupp5wmhqko.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vnfwwpoh5v4vofes.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'squirrelzarhffxz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iyeof5gg42xv2nao.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'n7kr26tlb545urpo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kotoqx6mdjabgumf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'w7pczrxaq6pamzov.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'macspy423ho54vap.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kzpajyms6plr7wo2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '54ogum7gwxhtgiya.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pfoxkj3p65uyc5pe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tpvj6abq225m5pcf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'elx57ue5uyfplgva.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qubesos4rrrrz6n4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fz474h2o46o2u7xj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wqfhdgpdelcgww4g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kkkkkkkkkk63ava6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bskoid4l5redrw5m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jvauzb4sb3bwlsnc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nz544wppkixoqajp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3pq7hs3cxj7xzuqn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4qt45wbulqipigwa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5j7saze5byfqccf3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'aaouiyrt23njidey.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fqnqc7zix2wblwex.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gl3n4wtekbfaubye.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jratiejtelswmbov.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nbybwh4atabu6xq3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vcahcomoh2aji6dl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6nefp5kt5yibi25s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kzspryu63qbjfncp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'secrdrop5wyphb5x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qkjscem7kksghlux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'raasbrrypzkuj5cy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ranionjgot5cud3p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'satan6dll23napb5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cfudbizo5i5r6lf6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fauftpffbmvh3p4h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sn4do42tm2hlnxeh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'offpriv2kalk6oya.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nfkrkvghv75xsf26.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'greynoiselgbq2l2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fbitipsu2i6rqii5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'irc2p5zrbdk25rdy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '26hundred5fmmcj2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'itemnaaj35zkkako.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'carsukikmh6hou73.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6dvj6v5imhny3anf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hackcanl2o4lvmnv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vb75uj2ap3hyyava.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nfs6e454oyvajfro.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'y2mpszcco2xuii4s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xhackergnluw32xz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hacksgq7qg4ejh3b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'crackersccqxsmdb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hehehekcec23tx3h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dwyqfuzdvdxyi6tl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pirateif6v33chtt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'grhacheapdtcawau.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'r44debe5ynev2udn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fsv2bgli7wk4hkvl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jokerbuzzhyhl5cl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blackhost5xlrhev.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4xzg7em4btak4lnu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yukoni2bjn5woljf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hackarmgq2n2erux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'netflixxb32gnsvy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hackharhoaw3yk5q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sipherl2xokvirou.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'edfbn5gfuaj2bc2w.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mre36vzwos4nng3h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oshix7yycnt7psan.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bylu6d6nx3og7shy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'casesvrcgem4gnb5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mdnhpj24s5a4soei.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'o4eahdlslz2y6j2q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jokeroodgo3ylved.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hashcrack25qkmjy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dostol2y24ehnl6b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'j36f2zfz7v3neai7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wqekut2pocn45hwp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bzcm5vrvtpbw5qbh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cra7yxjpxjila3bd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rinbfukwjetzcmmp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5fcdrnnrag6pdh6h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2hacklayurwqkgh2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mggenoj6brpkt3je.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'distropbucaekpgf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'atlas777hhh7mcs7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gunsdarkhzyowteb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vi5ydynhfco62g4v.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dtkeubgx47jeqvag.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7p4phtqnrzrg5ju5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'armoryx7kvdq3jds.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'g4r2pz2r22ztdcsm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6xbcodgrkz3tffpv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xjj6wjpujmh4evkb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'i2vpnraen5bggqge.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'haxedcwi5duu363s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tordoxov3jitflky.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sdata7sidixxhxpb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pbzl5p2uyganwo3k.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'aeriszyr4wbpvuo2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'atlantispvza4ylp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'stormwayszuh4juycoy4kwoww5gvcu2c4tdtpkup667pdwe4qenzwayd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'r22ecjdaqqlzd7jnori7eknbssiy4n4gnzy6aqkaba7amza7cfssc2yd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'aeris4pryl7r6x7yuqztr6pizv7pflb73wi6rqq7ty7f6sn5nvnmqdad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5s52mbyesidzzzlmtl5m4tsmewbcousk36gefrqnv7gk4lkstwms4byd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2ewf7o7sq7c3x2wkslt3omfplfoeazxe6uyakrg2wo5xhntokm3allyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cgpmsltmutyogck3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wallstyizjhkrvmj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'azworldjqhsr4pd5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tochka3evlj3sxdv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'valhallaxmn3fydu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'paranoid2ezdphvm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gurochanocizhuhg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'endchan5doxvprs5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oxwugzccvk3dk6tj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 't3e6ly3uoif4zcw2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '76ssfjn22svo4vyl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nytimes3xbfgragh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'e2byufqft24mg4wm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deepdot35wvmeyd5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tinhat233xymse34.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xvideos24y74huqj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gjgbztmown7d6usl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mr6temcirwiezfyr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'akvilonom27p5hvb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cmnlpnfm2setqvt2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '35flmpspwpnarbos.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xtcpromoiycayxhd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cardhous2l54npa3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'trinixy73gm6z4fq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'applekfwov4jebmr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ljekq2ejc62q76dy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'etrrdbuorwng2hkw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2wkwv7m4hetvqo3d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2iec4gqs2n4pucl7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cardedlxzxsphu5y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mobileay2syyw6qf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'electrotev3tgo2p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'techshop255zo43b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'amazonfkuuy6g3ou.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitstorenctdwhmo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cardtecdxboivkro.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xym5qdjlqrpq2rj7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rechardsp4x6tdrh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dollzucjzqg3coec.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5zkfuvtrpotg2nzd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ftec4org3hcpnoir.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitstfya5jxnujtr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mobil7rab6nuf7vx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'applei7nkshrsnih.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'burner5paaxqyxyw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zn4ei5n3xddb3otv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sale24u3apkfx252.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bestshop5zc7t3mf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'applexhmkr5a6ka5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yq6mfhgnosbf5vx5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'riverktt2ehwujh3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'eahfd4bjvgklinmt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mstrvukytwy4t5ce.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ekts3pf67fee5aj3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fpxlam652egkg4xn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'amazonhh6bvisfdl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4mjc7ee6n6hcyspv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xdfyw626gw2sjvzxyaoggrwlaij552v23pyeabgh4cmlhncjmqhqtcad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zaoklnavsgzaxhf4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'redroomfing27toi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'syst3k2e5lysrei4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shadowznwuibgi7w.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5sa3b4b6zznmtghz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'snuffyknz5eb6spv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lfbg75wjgi4nzdio.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7qzmtqy2itl7dwuu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'totozzimg6zbvthl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mstdnelm5phqmrl7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mango7ujh3rmxgoh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'occ4c3gx3w5esnmn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'redditmoongroogs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'whw44onfpnrp2o2s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'psycnets7z6tvqpa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'steemlohs6air4h2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ctr6sd645k4vz5p7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'monajruhsdcl6hdl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'galaxy3m2mn5iqtn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rchg4jrkrw3ufzjb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'connectkjsazkwud.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'society44nlbxqdz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'atlayofke5rqhsma.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dreadditevelidot.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'currencyyphgehc7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3vcqxi2ncgzn5wo3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'typefacew3ijwkgg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gmoindowca2xzlmc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'time3yauvhyqeias.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2jv5r7k66ralyk3g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'asspainwkywd5wfs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'publicibkxahavzc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'myonionkrv2wwvoc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'devcenterds3qc5z.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'webde3vkni6mhr3v.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'market7ow7cuw2hz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rseli7wo3qog4jdn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cpbiijtwjyn4enzi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shopsat2dotfotbs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hiremew3tryzea3d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'classifiypdoaowa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nsimondyhzfm26dq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sharezfpcbrpia5y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'parckwartvo7fskp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jacob365f4qhg6or.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'evbe2k4syrvewwq3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cheenazap345z6a7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7zu7dsntxmttnqyt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'th2yjjp5cmsoxmmb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '6vl7m43fjahjwftl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'glowlandpvb6q2tl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pablo6zbxiijn5hd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blaze246uma23h7s.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mc6nld3smffo3vgm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pasternjaui2k53d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zerobinqmdqd236y.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'nzxj65x32vh2fkhk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4m6omb3gmrmnwzxi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'asocialfz7ncw5ui.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fjl4hb5fmkpyfhjh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '32ixi6myw3things.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qe4zohjnmtu4pn2a.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'abigispddied4mec.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'anna4nvrvn6fgo6d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kjk4qvgg6usnvwyh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kotnikdvbq6lnbfz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dweebyhexfberrix.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torc5bhzq6xorhb4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '42xlyaqlurifvvtq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'riotiakxtodn2gv5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'youmad6gb7kvr7if.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darknetco4i4prlp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'opalrwf4mzmlfmag.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oq2pviecmwp4smrj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'onionbr5zulufnuj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'roewfyjjhvmv6zbu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mqqrfjmfu2i73bjq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xpgylzydxykgdqyg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pilletubnarawosh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rjzdqt4z3z3xo73h.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dtt6tdtgroj63iud.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'allyourkotatxek4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gac5e64yd3rsdk5n.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torsniffrqvvkv4x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tinywwyrr6ikpl7n.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'enotegggr635n4lw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cryptorffquolzz6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rrydrab7aba7hilt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dogshith5ciwa5ua.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '62gs2n5ydnyffzfy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hardblush4fncbgz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'antennazptyzyfpk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gnvweaoe2xzjqldu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hs5lugq65rtwf2l5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gccveylao63atwzy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ybrmt22in6gw2rtz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dvwae436pd7nt4bc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'psychk3hrpclistd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'obscuredtzevzthp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4xj2ajktkwlt7qza.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shhhhhh27fl6qr4b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ffc53e6cnzs7huej.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qkndirty6fifcrdk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kd2torrloy4oldux.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rlmhcda2ttz4tdtw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7y2ubp42h7afwii5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5qzfwb54nfw36tpb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'q7gfvo4mffwruqch.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'whisper4ljgxh43p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'soylentkxgydn6bz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bqi4yyxcu5rzxv3x.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'icxe4yp32mq6gm6n.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torwalkielhk4dxp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cdvuvwn35uwd7r22.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wyrgx7vaq7rj4tbp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dnadsjkrk57cd2fu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'maqsh3csot4l7svq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'uept3jzdzzixuq4w.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yniir5c6cmuwslfl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dark3dxwtzxnsyvh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitvoterh3qoeajo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'u5ed42u6sbzq7xzs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'e5dyelosweg6432w.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fj5zgzregjdcc3z3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dronecyllgl7x5w4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5oqsjgn37qnwrsg6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bwhalechnqlltea5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ka2mt4awglkwacog.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'milkwxjpscr54dlm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'creepymhpgibsewr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mymji3a2duev7jp2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'openforknet5sod6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'toiletfajyux53im.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yhmsoga4lk4bclfy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tordirhwtq6p7qcq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'astarotyn5uilwx2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'boot4jdrohd2iljy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'campi7y7dwwk6tue.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'artgalernkq6orab.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'papersqqyihp5b6u.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'latln6xmsn7pax3v.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hbooruahi4zr2h73.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'thund5izs5eyl254.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gfzw3wyc5lzbro4d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gkf352hyigqoan2g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'njto3uretienojic.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lolicore75rq3tm5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bgyar6b644c33joc.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'data44v2jfxk46ma.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dnjobs7e4z3zt7wa.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3osrqwtogzehxnw4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zv5wepan4gwbd3su.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tuxwnbupvdnfnwnd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blkbook3uvmlfmu3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'deadnotejlktdu6u.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '76qugh5bey5gum7l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qbj5eznyjs5q7rok.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'etnkdf2jsvc7vi4u.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bq6reuo2mxnlf5jb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'i4pvwlyicin2uuahmtewmanefgk6dpkhgpn6fazz2alh6d5tvptapyyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'y6olst6cvewp2eajoxpq6o5lywa253vo2ovhj226r2ihwq5ocbp34uqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'qtv2irkhu75xu2fybqa7g3ptjlhcnkfqimgzf35gqw6f24feai7jcpqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 't6fl7cybo2dhuszcbcxwrvziwzddc25uz3jeitw6j242uur6x2ant6id.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3g2upl4pq6kufc4m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hss3uro2hsxfogfq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xmh57jrzrnw6insl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3bbaaaccczcbdddz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'haystakvxad7wbk5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'abikogailmonxlzl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'searx7gwtu5rh6wr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'grams7enufi7jmdl.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sinbad66644fr5lq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'carontevaha5x626.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dark23456yyx57ny.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5u56fjmxu63xcmbk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'o2jdk5mdsijm2b7l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tor77orrbgejplwp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darkdirmpmoq3uur.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'visitorfi5kl7q7i.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '7cbqhjnlkivmigxf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torlinksccquz7bi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'underdj5ziov3ic7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jh32yv5zgayyyts3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yvmpwsd7vlxp2zgt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wikilink77h7lrbi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'khdwk3olxr3kip2p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'frwikisfa6myvgyx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'linklistpugaiwpi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tt3j2x4k5ycaa5zt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'linksvgkrmdzguvo.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'directdal7bourmy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5zf5yc2vwcnxgugv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'auutwvpt25zfyncd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'reviewef2jhdet6c.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'tmxwwir2rbxakwmi.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '36ctf62npcyhbgcd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'uhu7jakqd6ttrqlw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'gmfvhgkue66ejbfg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'rlrubc7so5acoie7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '4wqi32lc4xit3nb7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'iso2qqewfaemeifx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'doe6ypf2fcyznaq5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'relatecxjngl4qs7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'befrpwfinqkww32q.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'noscamkyvvxd7dk5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'auutwvpt2zktxwng.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oniondrlb455ed4l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'jdpskjmgy6kk4urv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'masterlistwtfzgt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dirnxldxoyajdetq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pdizimmrq5mwjkun.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'link2oeowhl73s7m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'n2ha26oplph454e6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wikitjerrta4qgz4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'phobosxilamwcg75xt22id7aywkzol6q6rfl2flipcqoc4e4ahima5id.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'oxytphxqnhsmnonmqodazmajpbtminlpmob72cpzmjmrvedp6ihp4lyd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'azsdjxck6kqdm7oz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mx7rwxcountermqh.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '52wdeibt3ivmcapq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '5h5ps743nnqsjq4l.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3wcwjjnuvjyazeza.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'inclibuql666c5c4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xsold3pvbxt4xblv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'akmb7t5w56jcfgwf.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'clivl6rf3vft7ihw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'genotypeinczgrxr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kgycm2bjsc75u4ac.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'clockwise3rldkgu.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'fb2lib3argrtulnw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'flibustahezeous3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hackerw6dcplg3ej.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'k2r5psouiawfu6jy.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'papyrefb2tdk6czd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zlibraryexau2g3p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'xfmro77i3lixucja.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wis45idjhhbgemez.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3cvpkfx4gdnkcduj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3cpleimu2getp5q7.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ibgk7stvp6bov6x6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'castorz2lijmrc5f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'h2am5w5ufhvdifrs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'v3bpt2x7iuz3gr2n.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'yuxv6qujajqvmypv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'r6rfy5zlifbsiiym.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'b2fxrnttdue72ntq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'avaxhome5lcpcok5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'muflax65ngodyewp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dembtxt2izv4tnpb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'twgl3hdma6bqbcyq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'omzbcj77hyizzfir.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'servnetshsztndci.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'godaddybqmlicbis.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torvps7kzis5ujfz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shyserversmg4gfe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dhosting4okcs22v.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'prometh5th5t5rfd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'sollhs4nbdwwzka2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ptveinu2qb2c3be2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'aivnsjq66nqvedxe.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'chchchiasaeljqgs.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torhost3p7quiikq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'mwl3znktk7mqogdv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hosting6eun2mouw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'freedomqbueysrt3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dwebc5skmvqfr5g2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zf2hkdev4iykqna6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cb3robuo3hobodw6.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hostingkmq4wpjgg.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'onehost4o5jfwvop.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'whoopdjk7ftbhtrr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3nuwa555bojyptrb.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'garlic7ravilyupx.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'onionname3jpufot.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'onionvitae4u7l4m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'blkhosthx66xfdzm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ezuwnhj5j6mtk4xr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cv5yzgowpd7epeur.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ln6vyadk4hv3dnyt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pic2torxpvv5qxqp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hellpicywfpsf52b.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'cj3mys6ssndefezt.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'felixxxboni3mk4a.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'freedomsct2bsqtn.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pix2aes4x5fi4v5f.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'teenxxxbtl7wsllp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'darknetogs6pex5i.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'becoc24nqduxeqgz.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '77e3ej24zlvmghdk.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dynedlzyi34wgks4.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2xd5vx4bmadk7i2k.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'y6xjgkgwj47us5ca.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'lockmypxprzghj3g.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bcloud2suoza3ybr.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'dropperibhaerr2m.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'torpicxwcx5kwdvp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'turbod44gwmvxnu3.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'filegxngeeag634p.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'uo5ncae3hgdpjjpm.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'pastagdsp33j7aoq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'huztewtlbljggn3d.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'kwn6i5jng6bsow5z.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'zupyv3e5spdok6nw.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'im7ev6j5qkrqmofv.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ytxmrc3pcbv5464e.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '35khdgeiyit26syj.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ydtjl5cn3smvsork.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'coolnameokrzolnd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'wuvdsbmbwyjzsgei.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'vilasamxj3nyexl2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'bitservepd6bbxtq.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'shv34p5cckiljkww.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'd33pzjppzy7d37r2.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '2222zui5d3psp4v5.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'hostiysldm5iocpp.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'spore64i5sofqlfz5gq2ju4msgzojjwifls7rok2cti624zyq3fcelad.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh 'ydtaexmzjs5wokbafe5venp32zr7jj3q6ioaj2f3rc2ak7flde5ldpqd.onion' >> $LIST
$SCRIPTDIR/tor_extract_from_url.sh '3b6clio4syptsnvvtzyxifqvtizyazgyowpp3v5f7dj3mzmfhyoy4iyd.onion' >> $LIST

$SCRIPTDIR/purify.sh $LIST > $LIST2
NUMBER=`wc -l $LIST2 | tr -s ' ' | cut -f 1 -d ' '`
echo "Harvested $NUMBER onion links..."
$SCRIPTDIR/push_list.sh $LIST2
rm $LIST $LIST2
