"""On-demand page summarization via a local, self-hosted model - no
external API, no per-call cost, same zero-vendor-dependency rule
already governing classification.py. Calls a local llama.cpp server
(Qwen3.5 4B) over its raw /v1/completions endpoint, not chat
completions - see below for why.

Qwen3.5 is a hybrid-thinking model: its chat template normally emits a
<think>...</think> reasoning block before the real answer, and the
server's OpenAI-compatible /v1/chat/completions endpoint has no working
way to disable that (chat_template_kwargs isn't wired through in this
llama-cpp-python version - confirmed by direct testing, not assumed).
Left enabled, a single summary call burns 900+ tokens on reasoning
before ever reaching the answer, taking ~2 minutes on this CPU. The
model's own chat template shows the fix: when thinking is meant to be
skipped, the prompt is primed with an already-closed, empty
<think></think> block rather than generated by the model. Building that
exact prompt by hand against the raw completions endpoint - bypassing
the broken kwarg entirely - cuts a real request from ~120s to ~10s with
no loss in summary quality (verified directly, not assumed)."""
import os

import httpx

SUMMARIZER_URL = os.environ.get("SUMMARIZER_URL", "http://127.0.0.1:8081/v1/completions")
MAX_INPUT_CHARS = 6000
TIMEOUT_SECONDS = 60

SYSTEM_PROMPT = (
    "You summarize a single crawled dark-web page for an analyst. Be factual and concise - "
    "3 to 5 sentences. State plainly what kind of page it is (marketplace, forum, leak-dump, "
    "ransomware post, etc.) and what it contains. Never invent details that aren't in the text. "
    "If the text is too sparse or garbled to summarize meaningfully, say so directly instead of "
    "guessing."
)


def _build_prompt(title, text):
    user_content = f"Title: {title or '(no title)'}\n\nPage text:\n{text}"
    return (
        "<|im_start|>system\n"
        f"{SYSTEM_PROMPT}<|im_end|>\n"
        "<|im_start|>user\n"
        f"{user_content}<|im_end|>\n"
        "<|im_start|>assistant\n<think>\n\n</think>\n\n"
    )


def summarize(title, body_text):
    text = (body_text or "")[:MAX_INPUT_CHARS]
    if not text.strip():
        return None

    prompt = _build_prompt(title, text)

    with httpx.Client(timeout=TIMEOUT_SECONDS) as client:
        response = client.post(
            SUMMARIZER_URL,
            json={
                "prompt": prompt,
                "temperature": 0.2,
                "max_tokens": 300,
                "stop": ["<|im_end|>", "<|im_start|>"],
            },
        )
        response.raise_for_status()
        data = response.json()

    return data["choices"][0]["text"].strip()
